### ISSUE TITLE
Use golang-image instead of ca-certs for running the application

### ISSUE THREAD

**Issue by lukaalba** [jusbrasil/pingdom-exporter#4]
Hi there,

first of all, thanks for your work of setting up a Pingdom-exporter which works fine. Is there a reason why you are using the ca-certs image for running the app instead of the default golang-image? The golang-image includes bash so we are able to get credentials from vault and use them as environment variables. 

Thanks in advance

**Comment by lukaalba** [comment]
After understanding what Multi-Staging in Rocker means, I suppose that was a bad idea 

But what about an alpine image?

**Comment by danielfm** [comment]
Why? If the reason is to keep the image small, I think the image is already small enough (10.9MB as in the current `latest`)

**Comment by lukaalba** [comment]
As I said in the original post, we need a shell in the image. The current image does not have a shell, does it?

**Comment by danielfm** [comment]
Regarding your use case, you can probably use an init container and sidecar for performing this task.

**Comment by lukaalba** [comment]
We already use an init container plus sidecar, which place a file in a kubernetes pod. All we need is a source command to set the env var for the api token. I could be wrong but it is not possible to use a sidecar to set a pod-wide env var, right?

**Comment by danielfm** [comment]
> I could be wrong but it is not possible to use a sidecar to set a pod-wide env var, right?

Indeed I don't think that's possible. However, using a credential from Vault as an environment variable, how are you rotating these credentials on the fly? If the value is set as an environment variable, you can't change these without restarting the container.

I don't use Vault myself, but I think the way people usually do this is by writing the credential to a shared volume.  

Since there are no other requests for this, I'm not sure it's a good idea to introduce a shell to this image, since it might increase the attack surface. But while this doesn't change, feel free to use this image as a basis, or create your own images.

**Comment by lukaalba** [comment]
Alright then. Thanks for your help.
